### ISSUE TITLE
Donation alternative

### ISSUE THREAD

**Issue by oowxswmm** [aaronjwood/PortAuthority#1]
Is there a way to donate without using Google Play?

**Comment by aaronjwood** [comment]
Currently, no. I believe I'd run into issues with their ToS since any kind of transaction is supposed to go through them so they receive their 30% cut. There are a few Google groups postings that show some people getting in trouble for using PayPal or something else :-/

https://play.google.com/about/developer-distribution-agreement.html

If I took everything off of google play and just distributed the apks myself then I would be able to use whatever I want. Kinda sucks...
