### ISSUE TITLE
ip neighbor command throws exception on android 11

### ISSUE THREAD

**Issue by 5hahryar** [aaronjwood/PortAuthority#134]
Hello, I encountered a strange issue. I tried running the app on android 11 it worked fine, then I updated the compile and target SDK versions from 29 to 30 and then after a rebuild I restarted the app. After this change a few exceptions happened, but the main one that I'm concerned with is about running "ip neighbor" command to access the MAC address.
Running this command exits with this error: "Cannot bind netlink socket permission denied"
Now I'm wondering if this is related to the new restrictions on android or it can be fixed in some way?
Side question: Getting the MAC address of devices on network, is it not possible anymore on android? If that is the case, then how fing is doing it?

**Comment by aaronjwood** [comment]
Sounds like the same issue as https://github.com/aaronjwood/PortAuthority/issues/129

To your question, they have tightened things a lot in the newer versions of Android. Here is just one example https://issuetracker.google.com/issues/130103885?pli=1

**Comment by 5hahryar** [comment]
That is true, but like i mentioned Fing is doing fine and they recently published a new version that supports android 11, 12. So do you have any idea on how they are implementing this? like using NDK or something?

**Comment by BayLee4** [comment]
@5hahryar I just verified this, and Fing is effectively using the NDK to implement their "Native ARP" (if you decompile their APK you'll see it implemented in `libengine.so`).

I don't know what would be simplest method to achieve API 30 compatibility : maybe using the NDK to build a modified [ip](https://android.googlesource.com/platform/external/iproute2/+/refs/heads/master/ip/) binary which only implement the `neighbor` parameter, so that the rest of the code doesn't need to change at all?

**Comment by 5hahryar** [comment]
@BayLee4 I tried running a [sample code](https://lynxbee.com/sending-arp-request-and-receiving-arp-reply-using-c-code/) on a raspberry pi 4. It compiled and worked successfully but I had to use sudo.
I tried running the same code on an android device (SDK 31) inside an app called "Cxxdroid". It compiled but failed with this error: socket() failed : Permission denied.
I'm not sure if that's because I'm using a third party app to execute the code, or it's a restriction from android on raw sockets or something?
The code it self seems to be ok since it ran fine on raspbianOS.

**Comment by BayLee4** [comment]
@5hahryar Yes, we need a code that can run without root permission (so without having to run as `sudo` on Linux).
This is why I was suggesting using a modified ip, in fact we would only need to port the [print_neigh](https://android.googlesource.com/platform/external/iproute2/+/refs/heads/master/ip/ipneigh.c#194) function

**Comment by 5hahryar** [comment]
@BayLee4 I have no experience in C, is there any documentation that can help?

**Comment by BayLee4** [comment]
@5hahryar None that I can think of unfortunately, but I just finished to make a stripped down version of the `ip` command only keeping the `neigh` part, could you please test it on your Raspberry Pi? I tested it on a `x86_64` virtual machine, so I do not know if it works well on `arm64`.

Here is the [repo](https://github.com/BayLee4/ip_neigh), once cloned and in the directory just do `make` and see if there are errors (there should have only one warning). If there is no error, please run `./ip` and compare the output with the `ip neigh` command, the two outputs should be the same. 

(If either `make` or `ip neigh` isn't recognized, you can install them by running : `sudo apt-get install iproute build-essential`)

**Comment by 5hahryar** [comment]
@BayLee4 Thank you, I executed your code and it looks like it is working perfectly.
Here is the output:
`pi@raspberrypi:~/Desktop/ip/ip_neigh-main $ ./ip
192.168.1.1 dev eth0 lladdr e4:**:**:**:**:9c STALE
192.168.1.163 dev eth0 lladdr a4:**:**:**:**:07 REACHABLE`

`pi@raspberrypi:~/Desktop/ip/ip_neigh-main $ ip neigh
192.168.1.1 dev eth0 lladdr e4:**:**:**:**:9c REACHABLE
192.168.1.163 dev eth0 lladdr a4:**:**:**:**:07 DELAY
`

**Comment by BayLee4** [comment]
@5hahryar Nice! Hopefully it will also work on Android, I never used the NDK though, did you?

**Comment by BayLee4** [comment]
For the record the following [code](https://github.com/BayLee4/ip_neigh/blob/cf9f479cc1875eeb20573dea02c717930e351675/libnetlink.c#L173-L178) needs an alternative : 
```c
	if (bind(rth->fd, (struct sockaddr *)&rth->local,
		 sizeof(rth->local)) < 0) {
		perror("Cannot bind netlink socket");
		return -1;
	}
	addr_len = sizeof(rth->local);
```

As this is what isn't working currently (API 30 not allowing to bind on `NETLINK_ROUTE` sockets).

**Comment by 5hahryar** [comment]
@BayLee4 I also haven't used NDK but I'll try it on an empty project to figure it out.

**Comment by BayLee4** [comment]
@5hahryar Ok, I pushed a fix today in the [ip_neigh](https://github.com/BayLee4/ip_neigh) repo  for working around the API 30 limitation, so hopefully it will work as is once built with the NDK.

**Comment by 5hahryar** [comment]
@BayLee4 I created a [repository](https://github.com/5hahryar/CpTest) and added all your C files. It fails to build the project with this error: undefined reference to 'rtnl_dump_filter_nc'
If you have any ideas please open an issue on my repo. we can come back here when we have a working solution.

**Comment by BayLee4** [comment]
@5hahryar Sure, better not to flood this issue anymore. I'll open an issue in your repository.

Regarding the undefined reference issue, this is because you only added the [ipneigh.c](https://github.com/5hahryar/CpTest/blob/master/app/src/main/cpp/CMakeLists.txt#L33) source file (where all `.c` [files](https://github.com/5hahryar/CpTest/blob/master/app/src/main/cpp/Makefile#L18) should be added) in your `CMakeLists.txt`. But this is not the only issue, you're mixing C and C++ files, and [native-lib.cpp](https://github.com/5hahryar/CpTest/blob/master/app/src/main/cpp/native-lib.cpp) doesn't call anything related to `ip_neigh`.

Furthermore I believe it would be simpler to compile `ip_neigh` as an executable, then call it directly and parsing what's written into `stdout` (not to change anything in the [current](https://github.com/aaronjwood/PortAuthority/blob/development/app/src/main/java/com/aaronjwood/portauthority/async/ScanHostsAsyncTask.java#L149) code). Plus, dealing with string buffers is a bit painful in C, so I really recommend going this way.
