### ISSUE TITLE
crash on selecting hosts with "_" in hostname.

### ISSUE THREAD

**Issue by truetrup** [aaronjwood/PortAuthority#16]
After scanning hosts, when tap on host with symbol "_" in hostname for ports scanning application crashed.
Android 5.0.1 Nexus 5.

**Comment by aaronjwood** [comment]
This is probably due to the hostname being malformed. No special characters (including the underscore) can be a part of the hostname http://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_host_names

Additionally, when you try to set a hostname on linux by running `hostname test_host` it won't actually let you set it and throws the error "hostname: the specified hostname is invalid"

How were you able to get underscores in your hostnames?

**Comment by truetrup** [comment]
Looks like this is *nix system with manually edited /etc/hostname & something more.
![screenshot_2015-04-11-10-50-51](https://cloud.githubusercontent.com/assets/10182585/7100017/3bfd5f36-e033-11e4-9e24-676e73357f81.jpg)

**Comment by aaronjwood** [comment]
Yikes, are you able to get that changed somehow? I bet that'll cause chaos in some environments with other devices since it's breaking the RFC :)
