### ISSUE TITLE
Port-Range / TCP/UDP

### ISSUE THREAD

**Issue by Alesioxp** [aaronjwood/PortAuthority#23]
Hi there i've noticed a few things that would need a little enhancement if you ask me :)

1) Possibility to "type in" Port Range is there, but the app freezes rather quickly after having only scanned about 500-to-2000 ports of the possible 65535.

2) Possibility to select TCP/UDP (if it isnt already scanning for both)

3) Iam not sure if you conceptualized "Port-Authority" as an Intranet-only Port-Scanner but if not it would be really nice to be able to scan the own Server from the outside.

Other than that its a great tool which is extremly handy if you want to know the IP of the host(s) that are up on your local network ALTHOUGH the host name resolution is still kinda buggy (most networks except for the router are named "localhost")

Have a nice day! :+1:

**Comment by Alesioxp** [comment]
Whoops forget about the Port-Range, that feature is already there.

**Comment by aaronjwood** [comment]
Thanks for the feedback! Definitely some good suggestions :) I'm glad to hear that you find it useful.

Can I ask what phone/tablet you're using when you run Port Authority? The reason why I ask is because it's possible for old hardware to have a hard time handling scanning MANY ports like you mentioned. This is because, internally, I am using many threads which is one of the big factors that give Port Authority its speed.

Can you elaborate on the issues you're seeing with host name resolution? The tricky thing with resolving host names on a local network is that a lot of factors are up to the router as far as how it provides host names. For example, the router I have gives some weird values for my FQDN. Also, some routers won't provide DNS by default at all. What I think I should do is probably support DNS as well as NetBIOS/WINS to make sure I am able to get the most accurate information I can. This is on my todo list.

**Comment by aaronjwood** [comment]
UDP port scanning will come later. I think it's going to be a pain to do it in Java, especially without root access. The nmap docs and wikipedia have some good explanation on this https://en.wikipedia.org/wiki/Port_scanner#UDP_scanning

Ideally I'd want to drop down to C via JNI in order to have more control, but then the things I'd want to do would require root access which I don't want to enforce on users. I'll have to think about the best way to implement UDP scanning that's fairly accurate and reliable without being able to use raw sockets or JNI...

**Comment by aaronjwood** [comment]
I'll be rolling out 1.6 soon which will let you scan WAN hosts now. See 8932e6bc88a719d8a0a302c123afaca150784a66 :)

**Comment by aaronjwood** [comment]
I just rolled out 1.6.2 which should GREATLY improve the issue you're seeing with the app freezing when scanning many ports.
