### ISSUE TITLE
Question about Code

### ISSUE THREAD

**Issue by lifeanddeath** [aaronjwood/PortAuthority#24]
Hello, I was just trying to understand code but I didnt get the part where u defined NUM_THREADS variable as 16 in ScanHostAsynTask.java. why is it 16? and also  String parts[] = ip.split("\\."); in this line what exactly does this do ? thanks in advance. my eternal respect...

**Comment by aaronjwood** [comment]
I've defined `NUM_THREADS` as 16 in that part of the code because I didn't want to parallelize the work any more than that. It mostly has to do with the fact that I'm relying on ARP to scan hosts very quickly.

`String parts[] = ip.split("\\.");` basically splits a string into pieces using . as the delimiter. You need two backslashes so that the first one will escape the dot, and the second one will escape the first backslash. `\.` isn't a valid escape sequence with Java.

Hope that helps!
