### ISSUE TITLE
Potential Privacy issue

### ISSUE THREAD

**Issue by z751** [aaronjwood/PortAuthority#27]
I saw the commit that will track ANRs, crashes, ect.  Will this be an opt-in thing or at least optional as this is a privacy issue and I do not install apps that track and record any of my activity

https://github.com/aaronjwood/PortAuthority/commit/15d16ec6c522f182624a34073bae638607c57f4f

**Comment by aaronjwood** [comment]
Yeah, I'll be making this feature something you can turn on/off in the settings. I'm also sort of evaluating this solution and if it doesn't help me out very much I'll just be getting rid of it. I wanted to use it mainly to help track down some difficult issues that sometimes arise from the multithreaded pieces of the app. Also, some people run into resource issues due to the way I've threaded the scans and I wanted to see a more in depth view of their situation when that happens. 

If this particular implementation turns out to be very helpful I'll probably have it be turned on by default in the settings with the option of turning it off. Sound good?

Just give me a few days to get this in place. I have a full time job so I do this on the side when I can :)

**Comment by mhyqwvcu** [comment]
This also has the disadvantage of making the app non-free and therefore [ineligible](https://gitlab.com/fdroid/fdroiddata/commit/eacadfb6e7dd7f495df324af61d39d65cec525ad) for F-Droid. Would you consider creating a fully free gradle flavor to support your F-Droid users?

**Comment by aaronjwood** [comment]
I'm actually going to be removing this stuff tonight or tomorrow. I think it'll raise too many questions going forward and it really doesn't align with the philosophy of the app anyway. I would also never want it to affect the eligibility for F-Droid.

**Comment by aaronjwood** [comment]
Reverted 539bcc57b7584c2f997176511e9a522ee5cff9b5 8efaee3d30e19ea5ca0e7b2c8cf3adaa797e7556 c083346228ef615527972e72d85e7c7b7ffc3e35 92e3be80e9bc1d26c0c35a7120d00a22d3c4bd93 8b728547ca84c99fcc0f79d6eb3ba4f04f32181d fdbd7170d62b4bd8ef187ea0766d597e8e515955 15d16ec6c522f182624a34073bae638607c57f4f

Will make a new release later today.

**Comment by z751** [comment]
I suppose we should mark this thread as closed, then?

**Comment by aaronjwood** [comment]
Sure, just pushed out a new release with these changes (and some extra bug fixes)

**Comment by mhyqwvcu** [comment]
Thanks! I hope you are still able to achieve your development goals.
