### ISSUE TITLE
Support all private networks

### ISSUE THREAD

**Issue by lightonflux** [aaronjwood/PortAuthority#5]
_AFAIK_ the app only supports 192.168._._ at the moment, But not the other private networks. At least it failed in my 10._._.\* net. More precisely it only scanned the first 255 hosts in the net.

Here a nice list of private networks in IPv4:
https://en.wikipedia.org/wiki/Private_network#Private_IPv4_address_spaces

It would be great if the app would change the range of IP addresses according to the net.

**Comment by aaronjwood** [comment]
This is a good idea and I'd certainly be open to supporting scanning hosts on other subnets.

I'm a bit surprised that the host scan didn't work for you. I don't have 192.168. hardcoded anywhere in the source. In fact if you look here you can see that I am getting the first three segments from the network you're on but only scanning hosts 1-255 on that segment https://github.com/aaronjwood/PortAuthority/blob/master/app/src/main/java/com/aaronjwood/portauthority/runnable/ScanHostsRunnable.java#L30

How did you find that it's only working with 192.168.x.x networks?

**Comment by lightonflux** [comment]
Sorry that my post wasn't clear enough. English is not my first language (as you probably noticed).

It scanned in the 10.… network. But it stopped after the first 255 hosts. So there is no bug or failure, it just didn't scan all the possible host. It didn't fail to scan, but it "failed" to scan the **whole** network.

I think the best approach would be to detect the network class (A, B, C) and scan for appropriate amount of hosts. And it would be helpful if it was possible to enter an address range, just as the port range.

**Comment by aaronjwood** [comment]
No worries at all. I thought you meant that there was an actual error :)

I see what you're saying now. I still agree and will work on implementing this sometime soon. I could have an area to enter an address range to scan but I'm not sure how I feel about automatically scanning all hosts in the various classes. I think I would feel the need to put up a warning to the user beforehand since it would be fairly noisy on a network. If I ran a scan like that on my company's network I would certainly be contacted by the security team right away :)

Maybe the best solution would be to keep the functionality the way it is now so it still scans the network segment that you're on by default but also add a box for users to enter in an address range if they want to do a more in-depth scan.

**Comment by lightonflux** [comment]
Sounds great.

**Comment by thanset** [comment]
@lightonflux  @aaronjwood This is implemented by pull request #48.  Unfortunately I do not have a router that supports anything beyond a /24, but using mock data it was able to scan smaller subnets of hosts (/25, /26 etc).  There isn't support for defining you subnet, by rather it dynamically find the subnet you're on and determines the number of possible hosts.

**Comment by lightonflux** [comment]
Any ETA for the fdroid release of the next version with this feature? 

I could try to spawn a bigger and smaller net with my openwrt router (gl.inet 6416A).

**Comment by thanset** [comment]
@lightonflux I have a few things to work out on the pull request, I'm aiming to finish the code by this coming weekend.  @aaronjwood not sure how long it takes to push this out to f-droid.

**Comment by aaronjwood** [comment]
F-Droid should pick up the release automatically after a short time once the new release is made.

**Comment by aaronjwood** [comment]
This will be in the next release (thanks to @thanset for adding this https://github.com/aaronjwood/PortAuthority/pull/58)

I'll open another issue to address your request for a user specified range scan.
