### ISSUE TITLE
NIC Database

### ISSUE THREAD

**Issue by sniperle** [aaronjwood/PortAuthority#6]
How about including the NIC database from http://download.lamatricexiste.info/nic.db.gz (with possibility to update it manually and/or automatically) and displaying the manufacturer of each network card in the scan list ?

**Comment by aaronjwood** [comment]
Definitely, this has been on my list as one of the additional features for the next feature list.

**Comment by aaronjwood** [comment]
This is now implemented in the newest version (1.4.0). When viewing a host you should be able to see the MAC vendor and type. Instead of bringing in a database and worrying about keeping it up to date I'm calling out to an API which helps keep the APK size down :) Plus, they should have quicker updates that I would if I had maintained my own database and created an update service around it.

**Comment by qopisbel** [comment]
You don't have to maintain a database, users could have an option to refresh the database through a manual download.

**Comment by aaronjwood** [comment]
That's true. I wonder if I should do that instead of calling out to an api. The api provides benefits but maybe the act of sending mac's to it is too much of a con for most people. I should have thought more about how people would want it to work underneath.

**Comment by qopisbel** [comment]
I think there's a benefit in allowing the option of using the API, especially if only the necessary part of the MAC address is sent, and not the entire thing. The provider you chose supports that. Also, an encrypted connection should be used whenever possible(if it isn't already).

**Comment by sniperle** [comment]
Have a look at this old tool please.

It uses an offline DB which is updated automatically or by user request. 

https://rorist.github.io/android-network-discovery/

**Comment by aaronjwood** [comment]
Fixed in #11
