### ISSUE TITLE
some Vendors name are all capitalized...

### ISSUE THREAD

**Issue by Bartoloni** [aaronjwood/PortAuthority#83]
**this can fix it to look much better...**

```
public static String getMacVendor(String mac, Context context) throws IOException, SQLiteException {
        Database db = new Database(context);
        db.openDatabase("network.db");
        Cursor cursor = db.queryDatabase("SELECT vendor FROM ouis WHERE mac LIKE ?", new String[]{mac});
        String vendor;

        if (cursor.moveToFirst()) {
            vendor = (cursor.getString(cursor.getColumnIndex("vendor")).toLowerCase());

            vendor = vendor.replace("tp-link", "TP-Link");
            vendor = vendor.replace("giga-byte", "Giga-Byte");
            vendor = vendor.replace("ltd", "LTD");
            vendor = vendor.replace("hongkong", "Hongkong");
            vendor = vendor.replace("co.", "CO.");
            vendor = vendor.replace(" corporation", " Corporation");
            vendor = vendor.replace("inc.", "INC.");
            vendor = vendor.replace("computer", "Computer");
            vendor = vendor.replace("corporate", "Corporate");
            vendor = vendor.replace("hon hai", "Hon Hai");
            vendor = vendor.replace("htc", "HTC");
            vendor = vendor.replace("tinno", "Tinno");

            vendor = vendor.substring(0, 1).toUpperCase() + vendor.substring(1); //first always uppercase!

```

**Comment by aaronjwood** [comment]
Right now the DB is created and shipped with the application. I had parsed the list of OUIs from IEEE and put them in a basic SQLite DB. The end goal is to get to #45 which should get rid of issues with stale data.

If you're seeing data with mixed case I guess that's due to IEEE not formatting it in the way you expect.

**Comment by aaronjwood** [comment]
I wouldn't hardcode any of the vendor names. It's possible the data frim IEEE may change and make it so that your hardcoded values won't catch new cases. If the data coming into the database needs to be formatted I would run it through a generic formatter so that it can handle any and all future cases.

Have you reached out to the IEEE about their formatting? :)

**Comment by aaronjwood** [comment]
I sent a note over to the IEEE today. I'll update this thread if/when they respond.

**Comment by aaronjwood** [comment]
Didn't get a good response at all. I don't think they even read half of my email that talked about what/where/how I'm using their current stuff:

```
Thank you for your feedback. 

We have launched an new public listing to better suit the needs of our customers and those that utilize the listing.  You can now search for registry assignments here: https://regauth.standards.ieee.org/standards-ra-web/pub/view.html#registries

If you have further questions or would like to help us further improve the system, please reply to this email with the following information: 

1) What browser are you using to access the public listing? 
2) How are you using the results from the public listing?
```

**Comment by aaronjwood** [comment]
Related: https://github.com/aaronjwood/PortAuthority/issues/45#issuecomment-344368551

**Comment by aaronjwood** [comment]
https://github.com/aaronjwood/PortAuthority/issues/45#issuecomment-344659846

They don't seem to want to address any questions I ask them. Maybe you'd have better luck.
