### ISSUE TITLE
distinguish between smartphone and notebook

### ISSUE THREAD

**Issue by Bartoloni** [aaronjwood/PortAuthority#85]
doing a small check to port 80 can identify a Smartphone from a Notebook...
but where to place this port check?

Asus MAC (Smartphone/Notebook)
Samsung MAC (Smartphon/notebook)
Huawei MAC (Smartphone/HotSpot)

P.S. Microsoft smartphones and Apple smartphones are answering on port 80 (but are the only 2)

**Comment by aaronjwood** [comment]
Can you explain more about what you want to do here? Port 80 is generally for web servers unless someone is doing something custom. Any device using TCP/IP can listen on port 80 for whatever they want. Practically everything on the internet is listening/accepting on port 80 which means you have millions of different servers, raspberry pi's, desktops, etc. using this port.

How are you relating a network port to a specific class of devices?

**Comment by Bartoloni** [comment]
sorry maybe i'm wrong.. but looking at the port scan ... doing the open port scan on an Androdi device (smartphone) .. the list of ports are completely Empty...  this mean that checking a standard port (like 80... 135.. etc etc) the app can distinguish between android-smartphone and notebook (and for some macadress.. like ASUS/SAMSUNG/HUAWEI .. this check can identify betetr the device type)

**Comment by aaronjwood** [comment]
It's hard to say what device will and won't have open ports. A device that should never have any ports open might have some open due to malicious activity. AFAIK there's nothing stopping you from listening on a port in Android so developers might make use of this for some LAN feature(s). I don't think you can try to classify devices and say "XYZ devices should never have open ports" because there are just too many possibilities. It may be that they are perfectly legitimate too.

Regarding ports not being picked up in some cases: it all depends on how the port scan is being done. There are alot of factors at work here including how long the socket timeout is, if the device is applying some sort of temporary block when it detects a scan (think fail2ban, etc), plus more. Programs like nmap are very good for scans because they allow for all kinds of port scans. Alot can be done from apps like this because they are able to use root privileges (work with raw sockets, craft packets, etc) whereas Android apps cannot unless they are assuming their user base is people with rooted phones...which I am not :)

So in general, scanning ports is not a very concrete experience. It all depends on what you're scanning and the thousands of other factors involved. And remember, if there's malware at play then throw your assumptions out the door. Just because a device has port 80 open doesn't necessarily mean it's running a web server.
